---
- name: install and configure jenkins
  hosts: all
  become: yes
  tasks:

    - name: Ensure APT is Installed
      apt:
        update_cache: yes

    - name: Install opedjdk
      apt:
        name: 
          - openjdk-17-jre
          - fontconfig
        state: present


    - name: Add Jenkins key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repo
      shell: 
        cmd: |
          echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list

    - name: Ensure APT is Installed
      apt:
        update_cache: yes

    - name: install jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure jenkins is enabled
      service:
        name: jenkins
        state: started
        enabled: yes
