---
- name: Install and configure Jenkins
  hosts: your_target_hosts
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install OpenJDK 11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present

    - name: Install Maven
      ansible.builtin.apt:
        name: maven
        state: present

    - name: Add Jenkins repository key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        filename: jenkins
        state: present

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present
        update_cache: yes
